### PR TITLE
Optional Note visible in Mac OS notification ?

### PR DESCRIPTION
**Pull request by Boumy**
Hello. I greatly appreciate your app. 
Could it be possible to add the word(s) we set after the action name in the Mac OS notification ? 
It could be useful for the "tc Last" action for example. And also useful to display in the notifications center of Mac OS.
What do you think about this ?
Thank you.

### CODE REVIEW

**Comment by dpap31** [comment]
Sure. That shouldn't be too difficult. I will look into it. Let me know if you have any other enhancement ideas.

**Comment by dpap31** [comment]
FYI, I will work out of this issue: #5. If you have other ideas for enhancement feel free to create an issue.

**Comment by Boumy** [comment]
Thank you very much. Will we be told when the update is online?

**Comment by dpap31** [comment]
@Boumy yes the update is deployed. You can get the new version here:

http://www.packal.org/workflow/timeclock

**Comment by Boumy** [comment]
Thank you. It works very well.

For your next "major release", I suggest: 
when typing "tc last", the text of the "note" would be displayed directly in Alfred's list of result.
But there is more: if we type "tc pending" (or another keyword) we would see a list of not stopped activities. ;) And if we press the down arrow to reach one of them (or the only one still unstopped) and press Enter, we stop that activity.

**Comment by dpap31** [comment]
@Boumy great ideas! I will look into these enhancements and get back to you.

**Pull request closed without merging**
